### ISSUE TITLE
add graphs to the README

### ISSUE THREAD

**Issue by maelle** [ropensci/monkeylearn#10]
See @leeper's comment in https://github.com/ropensci/onboarding/issues/45

**Comment by masalmon** [comment]
Or maybe a link to the post prepared in https://github.com/masalmon/first_7_jobs once it's published, possibly "stealing" one bar plot from it.

**Comment by masalmon** [comment]
Link to the post added.

**Comment by maelle** [comment]
The README should become minimal once the pkgdown site is up.
