### ISSUE TITLE
Add a .keep_all option to retain the other columns of input

### ISSUE THREAD

**Issue by aedobbyn** [ropensci/monkeylearn#100]

**Comment by maelle** [comment]
Oh good thinking 👌

**Comment by aedobbyn** [comment]
The more I just use the package the more I notice where it can be improved — the cycle may never end! 😆

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by aedobbyn** [comment]
I wonder what the best ordering of columns is here. Right now I'm thinking

`<other columns> <input column> <response columns>`


I think that makes the most sense because it bridges original input columns with output columns. The only downside is that it may mean columns get reordered if, in the original input, the order was

`<input column> <other columns>`


Also, planning on now retaining the name of the input column (if it's supplied) rather than renaming it to `req` as we had been doing.  So for instance:

```
library(magrittr)
library(monkeylearn)
text1 <- "Hauràs de dirigir-te al punt de trobada del grup al que et vulguis unir."
text2 <- "i want to buy an iphone"
text3 <- "Je déteste ne plus avoir de dentifrice."
text_4 <- "I hate not having any toothpaste."
request_df <- tibble::tibble(txt = c(text1, text2, text3, text_4),
                             other_col = 1:4)
monkey_classify(request_df, txt, unnest = FALSE, .keep_all = TRUE)
#> Using classifier ID cl_oFKL5wft; to find other classifiers, run monkeylearn_classifiers() or visit https://app.monkeylearn.com/main/explore/
#> Processing batch 1 of 1 batches: texts 1 to 4
#> # A tibble: 4 x 3
#>   other_col txt                                             res           
#>       <int> <chr>                                           <list>        
#> 1         1 Hauràs de dirigir-te al punt de trobada del gr… <data.frame […
#> 2         2 i want to buy an iphone                         <data.frame […
#> 3         3 Je déteste ne plus avoir de dentifrice.         <data.frame […
#> 4         4 I hate not having any toothpaste.               <data.frame […
```

`other_col` comes before the input column, `txt`, and we retain the name of `txt` rather than renaming it to `req`.

**Comment by maelle** [comment]
This is all so well thought 👏

**Comment by aedobbyn** [comment]
Thanks! Should be interesting to get feedback on whether people find the behavior intuitive or not 😄

**Comment by maelle** [comment]
I hope the blog post will bring new users to the package !

**Comment by aedobbyn** [comment]
Yes! 🤞
