### ISSUE TITLE
See if we can figure out why inline R chunk blocked pkgdown from rendering vignette

### ISSUE THREAD

**Issue by aedobbyn** [ropensci/monkeylearn#101]
See https://github.com/ropensci/monkeylearn/pull/98#issuecomment-375923299

**Comment by aedobbyn** [comment]
Nuked the whole `docs` directory and rebuilt from scratch, but still got the `Error in eval(expr, envir, enclos) : object 'speedup' not found` error ☹️

**Comment by maelle** [comment]
ok! thanks for trying!
