### ISSUE TITLE
Gracefully handle 422 errors

### ISSUE THREAD

**Issue by aedobbyn** [ropensci/monkeylearn#116]

**Comment by maelle** [comment]
not sure about "gracefully" though 😹

**Comment by aedobbyn** [comment]
I wonder how to set up a test for this...any ideas?

**Comment by maelle** [comment]
Yes yes cf #41 I want to replace `httr` by `crul` in the next version and use `webmockr` to produce errors. 😀

**Comment by aedobbyn** [comment]
Ahhh cool you're a (or many) steps ahead of me!
