### ISSUE TITLE
Add ability to assign multiple classifications/extractions to the same input text in one call

### ISSUE THREAD

**Issue by aedobbyn** [ropensci/monkeylearn#117]

**Comment by aedobbyn** [comment]
Not sure if MonkeyLearn will support this an there may not be a huge demand for it

**Comment by maelle** [comment]
monkeylearn has now been archived as no new maintainer could be found.

Someone could still volunteer to take it over / write a new one. https://devguide.ropensci.org/curationpolicy.html
