### ISSUE TITLE
Add R-centric way to train a custom MonkeyLearn module

### ISSUE THREAD

**Issue by aedobbyn** [ropensci/monkeylearn#129]
Haven't looked into what this would entail yet!

https://monkeylearn.com/blog/how-to-create-text-classifiers-machine-learning/

**Comment by maelle** [comment]
monkeylearn has now been archived as no new maintainer could be found.

Someone could still volunteer to take it over / write a new one. https://devguide.ropensci.org/curationpolicy.html
