### ISSUE TITLE
Using Keyword Extractor returns error if no keyword is found

### ISSUE THREAD

**Issue by asjlyle** [ropensci/monkeylearn#13]
If no keyword is found using the keyword extractor then an error is returned e.g running

monkeylearn_extract(request = "hello", extractor_id = "ex_y7BPYzNG")

returns the error:

Error in vapply(temp$result, nrow, FUN.VALUE = 0) : 
  values must be length 1,
 but FUN(X[[1]]) result is length 

Meaning this function breaks loops if trying to iterate over rows in a data frame.

Is there any solution to this?

**Comment by masalmon** [comment]
Great catch @asjlyle, thanks for reporting this bug!

I've just committed a change, now you'd get

```r
> monkeylearn_extract(request = "hello", extractor_id = "ex_y7BPYzNG")
No results for this extractor call
# A tibble: 0 × 0
```

Does this solve your problem?

**Comment by masalmon** [comment]
@asjlyle was *this* problem solved by the way?

**Comment by asjlyle** [comment]
@masalmon I wasn't able to test it unfortunately. As a work around at the time I used try() in the loop so that when the monkeylearn_extract function returned an error it skipped it. I will test it as soon as I can, but right now I am experiencing an an issue meaning I can't run the monkeylearn functions at the moment (other open issue about curl error)

**Comment by masalmon** [comment]
Ok @asjlyle, no problem 😊

**Comment by masalmon** [comment]
It looks like an obstacle course @asjlyle, I'm sorry about that and really hope installing the development version will solve all your problems and if it doesn't we'll find a solution.

**Comment by masalmon** [comment]
@asjlyle can you please test the keyword extraction from the development version?

**Comment by maelle** [comment]
I'll consider this solved.
