### ISSUE TITLE
Please use git tags and release notes

### ISSUE THREAD

**Issue by sckott** [ropensci/monkeylearn#131]
Could you please make sure to git tag each CRAN release https://github.com/ropensci/monkeylearn/tags - looks like you've tagged the first CRAN release, but have missed the last two

And plop in associated NEWS items for each release - thanks! e.g., https://github.com/ropensci/taxize/releases/tag/v0.9.3 

These two things make it easier for people to find the associated changes with each new version

**Comment by maelle** [comment]
Good catch thx a ton! Now done https://github.com/ropensci/monkeylearn/releases/tag/V0.2.0
