### ISSUE TITLE
Add .gitattributes file

### ISSUE THREAD

**Issue by aedobbyn** [ropensci/monkeylearn#136]
Containing 

```
* linguist-vendored
*.R linguist-vendored=false
```

as per https://twitter.com/SuzanBaert/status/987622555681984513 

😺

**Comment by maelle** [comment]
No need to though, isn't this repo already classified as R? 🤔

**Comment by aedobbyn** [comment]
Ah you're right, I was looking at my fork!

**Comment by maelle** [comment]
Ah interesting! Good thinking in any case, I've made quite a few PRs with linguist stuff last week so I'm happy you thought about this 😸

**Comment by aedobbyn** [comment]
😄 it's been on my todo list for forever, such a neat little trick!

**Comment by maelle** [comment]
I've used for ropensci repos that had docs in non standard places e.g. https://github.com/ropensci/ecoengine/pull/95 and that had JS code that wasn't from the repo https://github.com/ropensci/wellknown/pull/26

**Comment by aedobbyn** [comment]
Ahh very cool. I guess GitHub goes by total summed file size rather than by number of files with a certain extension. Probably makes more sense to do the latter, imo

**Comment by maelle** [comment]
Interesting, not sure which one I prefer. What annoys me is that the classification of a repo is binary. For R packages with a lot of C++ code it's great to have them discoverable by their containing C++ code of course but it's not very cool to have them classified as C++ repo... Btw I added the "r" and "rstats" topics to all ropensci packages, so at least one can search "topic:r" if not "language:r" 😀 (sorry @aedobbyn I have so many opinions after spending time on this recently ahahah now I'll stop ranting)

**Comment by aedobbyn** [comment]
Oh nice!! You've thought a lot about this I can see 😄 I wish we could tag @github here...
