### ISSUE TITLE
More info on http errors available?

### ISSUE THREAD

**Issue by Arf9999** [ropensci/monkeylearn#137]
Can someone point out how to identify the http errors received.

I've just installed monkeylearn and have tried to classify a column from an existing dataframe. On the first run it classified the first 200 (of 1168), and then failed with with http errors for subsequent 200 iterations. Then the `cbind` failed due to mismatch of rows.

After checking API key, classifier, syntax looks correct, I've tried again and now can't even get the first 200. I'd like to see what the actual http error code received is in order  investigate further, any way to do this?

My code (`streamdata` is an `rtweet ` twitter stream dataframe with 1168 observations of 42 variables):

```
devtools::install_github("ropensci/monkeylearn")
library(monkeylearn)
monkeylearn_key <- "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
classifier <- "cl_qkjxv9Ly"

monkey_sentiment <- monkey_classify(streamdata, col = text, key = monkeylearn_key,
                                    classifier_id = classifier, params = NULL, texts_per_req = 200,
                                    unnest = TRUE, .keep_all = TRUE, verbose = TRUE)

```
This is the error response from monkeylearn:
```
Processing batch 1 of 6 batches: texts 1 to 200
Pause for http error, wait & try number 3
Pause for http error, wait & try number 4
Pause for http error, wait & try number 5
Pause for http error, wait & try number 6
Pause for http error, wait & try number 7
Pause for http error, wait & try number 8
Error in cbind_all(x) : Argument 2 must be length 1168, not 200
```

**Comment by aedobbyn** [comment]
@Arf9999 thanks for submitting this issue. You bring up a good point that providing more HTTP error information will be useful for users. Unfortunately, all I can tell from the error you got was that the status code was >= 400.

Just to check off the bat, did you create your own API key on MonkeyLearn and follow the [setup instructions](http://ropensci.github.io/monkeylearn/articles/monkeylearn_intro.html#setup)?

Separately, I want to make sure that the `unnest = TRUE` option works well for this classifier. Once you've saved your credentials, would you please install a different version of the package with an unnesting tweak using `devtools::install_github("ropensci/monkeylearn", ref = "T137-twitter-error")`. An example using that version of the package and the particular classifier:


```
library(monkeylearn)
tweets <- rtweet::search_tweets("foo", n = 5)
#> Searching for tweets...
#> Finished collecting tweets!
monkey_classify(tweets, text, classifier_id = "cl_qkjxv9Ly", texts_per_req = 2) 
#> Processing batch 1 of 3 batches: texts 1 to 2
#> Processing batch 2 of 3 batches: texts 2 to 4
#> Processing batch 3 of 3 batches: texts 4 to 5
#> # A tibble: 5 x 46
#>   status_id      created_at          user_id      screen_name  source     
#>   <chr>          <dttm>              <chr>        <chr>        <chr>      
#> 1 1005391501365… 2018-06-09 10:09:47 634086746    alanstand    Twitter fo…
#> 2 1005391487205… 2018-06-09 10:09:44 2385471312   angiee1_cx   Twitter fo…
#> 3 1005391420809… 2018-06-09 10:09:28 85971293358… KRTIT_KRKNS  Twitter fo…
#> 4 1005391396465… 2018-06-09 10:09:22 84676275284… Pp_foo       Twitter fo…
#> 5 1005390981649… 2018-06-09 10:07:43 78813647355… fuck_you_ed… Twitter fo…
#> # ... with 41 more variables: reply_to_status_id <lgl>,
#> #   reply_to_user_id <lgl>, reply_to_screen_name <lgl>, is_quote <lgl>,
#> #   is_retweet <lgl>, favorite_count <int>, retweet_count <int>,
#> #   hashtags <list>, symbols <list>, urls_url <list>, urls_t.co <list>,
#> #   urls_expanded_url <list>, media_url <list>, media_t.co <list>,
#> #   media_expanded_url <list>, media_type <list>, ext_media_url <list>,
#> #   ext_media_t.co <list>, ext_media_expanded_url <list>,
#> #   ext_media_type <lgl>, mentions_user_id <list>,
#> #   mentions_screen_name <list>, lang <chr>, quoted_status_id <chr>,
#> #   quoted_text <chr>, retweet_status_id <chr>, retweet_text <chr>,
#> #   place_url <chr>, place_name <chr>, place_full_name <chr>,
#> #   place_type <chr>, country <chr>, country_code <chr>,
#> #   geo_coords <list>, coords_coords <list>, bbox_coords <list>,
#> #   text <chr>, confidence <dbl>, category_id <int>, probability <dbl>,
#> #   label <chr>
```

The last few columns, `confidence`, `category_id`, `probability`, and `label` are the MonkeyLearn classifications of each row of the `text` column of `tweets`.

**Comment by Arf9999** [comment]
Thanks for your response. 

I managed to find out what the error was (my team had exhausted the API calls!), but I think it would be great if the error response listed the error code.

Thank you for the advice regarding the alternative version. 

Closing this.

**Comment by aedobbyn** [comment]
@Arf9999 that's a bummer. If you like, can talk to our MonkeyLearn contacts to try to get you some more API calls since it was a limitation of the package that caused them to be used unnecessarily. 

Now that you figured it out, what was the error you received?

**Comment by Arf9999** [comment]
I don't know what the error was, I'm guessing 403. But shortly after posting the question, I received the update email from Monkeylearn to inform me what the issue was.

Thanks for the offer to reach out to them, but that's really not required.

**Comment by aedobbyn** [comment]
Thanks for the heads up, and let me know if you change your mind.
