### ISSUE TITLE
monkey_classify error

### ISSUE THREAD

**Issue by CDunhill** [ropensci/monkeylearn#140]
I'm getting this error message with the R package:

Warning: `cols` is now required when using unnest(). Please use `cols = c(res)`

This happens with any classifier, eg. Sentiment, id: **cl_pi3C7JiL**

**Comment by maelle** [comment]
@aedobbyn :wave:! Would you have time to look at the warning above? No worries if not.

@CDunhill Thanks for the bug report!

**Comment by CDunhill** [comment]
NP... apologies in advance if it's something I've done wrong!

**Comment by maelle** [comment]
no no it's most certainly this package not keeping up to date with tidyr evolutions!

**Comment by maelle** [comment]
monkeylearn has now been archived as no new maintainer could be found.

Someone could still volunteer to take it over / write a new one. https://devguide.ropensci.org/curationpolicy.html
