### ISSUE TITLE
ALl calls w. same error  // Error: 'as_tibble' is not an exported object from 'namespace:tibble'

### ISSUE THREAD

**Issue by sbastos01** [ropensci/monkeylearn#17]
HI,  Great to see this kind of work !  Cheers. S.

1. Running R in windows. Re-started the session 2 times. 
2. All other packages are fine.
3. The system pause - query your API and return with error.
4. my key is fine
Sys.getenv("MONKEYLEARN_KEY") 

Try to install possible dependencies ... DID NOT WORK .

, it seems it's just a forgotten dependency. From R :
install.packages("tibble") ; install.packages("plotly")

HERE THE ERRORS...
```
 output <- monkeylearn_extract(request = text, extractor_id = "ex_isnnZRbS")
Error: 'as_tibble' is not an exported object from 'namespace:tibble'
> output
Error: object 'output' not found
> output2 <- monkeylearn_extract(text,
+                                extractor_id = "ex_y7BPYzNG",
+                                params = list(max_keywords = 1))
Error: 'as_tibble' is not an exported object from 'namespace:tibble'
> output2 <- monkeylearn_extract(text, extractor_id = "ex_isnnZRbS",
+                                params = list(max_keywords = 1))
Error: 'as_tibble' is not an exported object from 'namespace:tibble'
> text1 <- "my dog is an avid rice eater"
> text2 <- "i want to buy an iphone"
> request <- c(text1, text2)
> monkeylearn_classify(request,
+                      classifier_id = "cl_oFKL5wft")
Error: 'as_tibble' is not an exported object from 'namespace:tibble'
> text1 <- "I think this is awesome."
> text2 <- "Holy shit! You did great!"
> request <- c(text1, text2)
> monkeylearn_classify(request,
+                      classifier_id = "cl_KFXhoTdt")
Error: 'as_tibble' is not an exported object from 'namespace:tibble'
```

**Comment by masalmon** [comment]
@sbastos01 thanks for the bug report! If you just write

```{r}
tibble::as_tibble()
```

what does it do?

What is the `tibble` version you've installed?

**Comment by sbastos01** [comment]
Thanks for checking...

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.5      withr_1.0.2      assertthat_0.1
 [4] digest_0.6.9     slam_0.1-35      R6_2.1.2
 [7] grid_3.3.1       plyr_1.8.4       jsonlite_0.9.22
[10] gtable_0.2.0     scales_0.4.0     ggplot2_2.1.0
[13] httr_1.2.0       curl_0.9.7       NLP_0.1-9
[16] devtools_1.12.0  RevoUtils_10.0.1 tools_3.3.1
[19] munsell_0.4.3    parallel_3.3.1   rsconnect_0.4.3
[22] tm_0.6-2         colorspace_1.2-6 memoise_1.0.0
[25] tibble_1.0
> tibble::as_tibble()
Error: 'as_tibble' is not an exported object from 'namespace:tibble'

**Comment by sckott** [comment]
looks like `tibble` v1 doesn't have `as_tibble` exported at least https://github.com/tidyverse/tibble/blob/v1.0/NAMESPACE

**Comment by sbastos01** [comment]
OK.

Should I install another version? install URL??

Cheers. S.

Cheers,
Sergio Bastos
I help the shift to red rabbit
+1-561.430.7667
skype: sbastos-ca
LinkedIn: http://www.linkedin.com/in/sbastos

**Comment by sbastos01** [comment]
FYI

---------- Forwarded message ----------

**Comment by masalmon** [comment]
@sbastos01 could you update tibble to v1.2 which is on CRAN ? Thanks for the report, I've written the minimal version number in  the description now. And thanks @sckott !

**Comment by sbastos01** [comment]
HI,

It seems I will need to change R version as well... getting an error when
installing
updating to 3.3.2

Currently at
64-bit] C:\Program Files\Microsoft\MRO-3.3.1


> install.packages("tibble ")
Installing package into ‘C:/Users/sergio/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘tibble ’ is not available (for R version 3.3.1)
> install.packages("Rtools")
Installing package into ‘C:/Users/sergio/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘Rtools’ is not available (for R version 3.3.1)




Cheers,
Sergio Bastos
I help the shift to red rabbit
+1-561.430.7667
skype: sbastos-ca
LinkedIn: http://www.linkedin.com/in/sbastos

**Comment by masalmon** [comment]
Tibble only depends on  R (>= 3.1.2).

Do you have des tools Installed?  Maybe you can try installing tibble from github . 

devtools::install_github("tidyverse/tibble")

**Comment by sbastos01** [comment]
Ok. Issue resolved. Thanks !

Re-installed >>> [64-bit] C:\Program Files\R\R-3.3.2
installed devtools for 3.3. X
installed /3.3/tibble/libs/x64

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.8     assertthat_0.1  dplyr_0.5.0     digest_0.6.9
 [5] withr_1.0.2     slam_0.1-35     grid_3.3.2      R6_2.1.2
 [9] DBI_0.4-1       jsonlite_0.9.22 gtable_0.2.0    magrittr_1.5
[13] git2r_0.15.0    httr_1.2.0      curl_0.9.7      NLP_0.1-9
[17] devtools_1.12.0 tools_3.3.2     parallel_3.3.2  rsconnect_0.4.3
[21] tm_0.6-2        memoise_1.0.0   knitr_1.13      tibble_1.2-13


Cheers,
Sergio Bastos
I help the shift to red rabbit
+1-561.430.7667
skype: sbastos-ca
LinkedIn: http://www.linkedin.com/in/sbastos

**Comment by masalmon** [comment]
Awesome, thanks again for the bug report!
