### ISSUE TITLE
monkeylearn_classifiers() bug

### ISSUE THREAD

**Issue by masalmon** [ropensci/monkeylearn#18]
When I use `monkeylearn_classifiers()` I now get the error

```
 Error: lexical error: invalid char in json text.
                                       <!DOCTYPE html> <html class="no
                     (right here) ------^ 
```

I'm not sure what changed in the `classifiers` endpoint. @feconroses have you noticed an issue on your side? If not, I'll look into the R code in more details tomorrow.

**Comment by masalmon** [comment]
What I get from calling the endpoint is a html page including "Oops, we had an unexpected error" and "Our developer monkeys have been notified and will be fix ASAP." so I'll let the 🐒 s do their job! 🐵

**Comment by rsteca** [comment]
Hi @masalmon! It seems to be a problem on our side. We will try to fix this ASAP. Sorry for the inconvenience.

**Comment by masalmon** [comment]
@rsteca thanks! I have to say I'm happy I'll just have to wait and do nothing :speak_no_evil:

**Comment by rsteca** [comment]
@masalmon  the endpoint should be working now. Tell me if you have any more problems.

**Comment by masalmon** [comment]
Wonderful @rsteca , thanks a lot, yes it seems to be working! :grinning:
