### ISSUE TITLE
Feed back  -- errors  -- Processing few semi- cleaned tweets

### ISSUE THREAD

**Issue by sbastos01** [ropensci/monkeylearn#19]
++++ Error 1 +++++++++++++++++++++
```r
Tweet was blank >>> [1] "         "
 
 Rerun with Debug
 Error: HTTP failure: 422 > df8c$t.message[53]
[1] "         "
3 stop("HTTP failure: ", req$status_code, "\n", content(req)$detail, 
    call. = FALSE) 
2 monkeylearn_check(output) 
1 monkeylearn_extract(request = text, extractor_id = "ex_isnnZRbS") 
```
+++++++++++  error 2   Timeout was reached   ++++++++++++++++++++++++
```r
 Rerun with Debug
 Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached 
9 curl::curl_fetch_memory(url, handle = handle) 
8 request_fetch.write_memory(req$output, req$url, handle) 
7 request_fetch(req$output, req$url, handle) 
6 request_perform(req, hu$handle$handle) 
5 POST(monkeylearn_url_extractor(extractor_id), config(http_version = 0), 
    add_headers(Accept = "application/json", Authorization = paste("Token ", 
        key), `Content-Type` = "application/json"), body = request) 
4 monkeylearn_get_extractor(request_part, key, extractor_id) 
3 tryCatchList(expr, classes, parentenv, handlers) 
2 tryCatch(monkeylearn_get_extractor(request_part, key, extractor_id)) 
1 monkeylearn_extract(request = text, extractor_id = "ex_isnnZRbS") 
```

**Comment by masalmon** [comment]
So the tweet is empty? Maybe first filter them ?

**Comment by sbastos01** [comment]
Yep. It seems the api should not fail on that... just warning??

**Comment by sbastos01** [comment]
Yep. It seems the api should not fa

**Comment by masalmon** [comment]
Yes I should add a warning and return NULL, but in the meantime (I might do it later today -- I live on UTC+1) please filter or use `try`, sorry about that. And thanks for the bug report! :+1:

**Comment by sbastos01** [comment]
Cool. I will keep sending any "bug like" ...

Cheers,
Sergio Bastos
I help the shift to red rabbit
+1-561.430.7667
skype: sbastos-ca
LinkedIn: http://www.linkedin.com/in/sbastos

**Comment by masalmon** [comment]
Yes, please keep reporting, after a while I'll hope there'll be nothing new to report. :grin:  Just a note on issues, I've re-formatted your bug reports to include R code and output between lines with "```" because it's then easier to read on the Github website.

**Comment by masalmon** [comment]
@sbastos01 can you test the development version of this package please?

Now if `request` is a single blank text, you get an empty `tibble` and a warning.

If `request` is a vector with parts that are blank text, you get a message telling you those blank parts are not sent to the API.

**Comment by sbastos01** [comment]
yes !! will try later on

Cheers,
Sergio Bastos
I help the shift to red rabbit
+1-561.430.7667
skype: sbastos-ca
LinkedIn: http://www.linkedin.com/in/sbastos

**Comment by masalmon** [comment]
Closing this now unless @sbastos01 re-opens it.
