### ISSUE TITLE
Invalid token header. No credentials provided

### ISSUE THREAD

**Issue by nujcharee** [ropensci/monkeylearn#20]
I am following the documentation but Im not sure which part I missed but I dont know how to add token header or my monkey learn API. 
Please could you advice?
Many thanks

**Comment by maelle** [comment]
Was this solved by comments on the blog post ?

**Comment by boulbi777** [comment]
I got exactly the same problem right now !

**Comment by maelle** [comment]
Thanks both

* had you been able to add your key previously?

* can you post an example of a code where you get the error?

Thanks :-)

**Comment by maelle** [comment]
And when you mean following the documentation do you mean

"To get an API key for MonkeyLearn, register at http://monkeylearn.com/. Note that MonkeyLearn supports registration through GitHub, which makes the registration process really easy. The free API key provides up to 100,000 requests a month For ease of use, save your API key as an environment variable as described at http://stat545.com/bit003_api-key-env-var.html.

Both functions of the package will conveniently look for your API key using Sys.getenv("MONKEYLEARN_KEY") so if your API key is an environment variable called "MONKEYLEARN_KEY" you don't need to input it manually."

?

Thanks

**Comment by boulbi777** [comment]
I tried the first example in this code section :

`output <- monkeylearn_extract(request = text,
                              extractor_id = "ex_isnnZRbS")`

But it doesn't work. 
Here is the error displayed :

> Error: HTTP failure: 401
Invalid token header. No credentials provided.

What's the problem ?

**Comment by maelle** [comment]
@boulbi777 have you registered at Monkeylearn and then saved your key as explained in "To get an API key for MonkeyLearn, register at http://monkeylearn.com/. Note that MonkeyLearn supports registration through GitHub, which makes the registration process really easy. The free API key provides up to 100,000 requests a month For ease of use, save your API key as an environment variable as described at http://stat545.com/bit003_api-key-env-var.html.

Both functions of the package will conveniently look for your API key using Sys.getenv("MONKEYLEARN_KEY") so if your API key is an environment variable called "MONKEYLEARN_KEY" you don't need to input it manually."

That may be the problem, if not happy to help trouble shooting.

**Comment by boulbi777** [comment]
No, I didn't register.
Gonna do it !
Thank you for your help ! @maelle  ! :+1:

**Comment by maelle** [comment]
Awesome, and don't hesitate report any difficulty or bug @boulbi777 !

Closing this for now as the person opening the issue told in a comment on my blog it had been solved.

**Comment by boulbi777** [comment]
Ok, great news !
