### ISSUE TITLE
create devel or dev branch

### ISSUE THREAD

**Issue by maelle** [ropensci/monkeylearn#28]
🚀

**Comment by maelle** [comment]
so wait I said things wrong. I think you can:

* create a devel branch in this repo

* change your PR so that it's a PR to the devel branch. I did that recently for a PR, using https://github.com/blog/2224-change-the-base-branch-of-a-pull-request

* merge your own PR

**Comment by aedobbyn** [comment]
Hmm think I don't have write access yet. When trying to push, "Please make sure you have the correct access rights and the repository exists."  and when tying to edit a file in GitHub I get "You’re editing a file in a project you don’t have write access to." 😕

**Comment by maelle** [comment]
Oh no I had forgotten one more setting to change. Now it should work, sorry about that!

**Comment by aedobbyn** [comment]
Great, worked out! The changes from the PR are in `dev`, and I've updated the `classify-df` branch with a new function `classify_vec()` which does the same thing as `classify_df()` except it takes a vector of inputs. Happy to discuss whether these should be two separate functions or, as is currently the state in `classify-df` branch, `classify_df()` should be able to accept either a dataframe and a named column or a vector.
