### ISSUE TITLE
build request_reconstructed in classify_df() from df[[col]] to preserve empty string rows

### ISSUE THREAD

**Issue by aedobbyn** [ropensci/monkeylearn#32]

**Comment by maelle** [comment]
you mean the rows with empty strings that the user provided because their text preparation method somehow produced empty strings?

**Comment by aedobbyn** [comment]
Right, exactly. If they have empty strings we filter them out with `monkeylearn_filter_blank()` then we'd return a dataframe without those empty string rows, which will have fewer rows than their input dataframe.

**Comment by aedobbyn** [comment]
I'd like to think of a better way of doing this than comparing the input request strings to the cleaned request strings since these may not be unique. If that's the case, we now have an informative error message on [line 167](https://github.com/ropensci/monkeylearn/blob/T32/R/monkey_classify.R), but probably not the best solution, so this is still on the T32 branch rather than in dev. Happy to merge in if you like.
