### ISSUE TITLE
attempt to remove dplyr and tidyr dependencies

### ISSUE THREAD

**Issue by aedobbyn** [ropensci/monkeylearn#33]
- try to bind rows with `rbind()` rather than `dplyr::bind_rows()`
- try to unnest rows without `tidyr::unnest()`

**Comment by maelle** [comment]
and if it takes too long, just forget about it and keep the dependencies, don't spend hours and hours on this. 😉

**Comment by aedobbyn** [comment]
Haha sounds good. If it's tough I might put this one to the R-Ladies and see what we come up with 😆

**Comment by maelle** [comment]
I actually noticed today I had `dplyr` as a dependency in another package 🤦‍♀️ but hey still better if we can avoid it.

**Comment by aedobbyn** [comment]
Haha it's so hard to get away from!

Which was the other package? I can add that to the issue description unless it would be impossible not to rely on `dplyr` for that particular task

**Comment by maelle** [comment]
which issue description?

the other package is `opencage` and I never received an issue from someone about its depending on `dplyr` (granted, I don't know how many users it has in the first place 😂 )

**Comment by aedobbyn** [comment]
Oh sorry -- this issue description (#33). But nevermind, I read you wrong and thought you meant there was another function in this package that had a `dplyr` dependency. `opencage` looks awesome (and super complicated)!

**Comment by aedobbyn** [comment]
Actually looks like `dplyr::bind_rows` is currently used in lines 107 and 108 of `extractor.R` on master. Maybe explains why I had trouble getting headers from `monkeylearn_classify()` but didn't with `monkeylearn_extract()`.

I see -- looks like the test written for headers checks whether the output is a dataframe, which is why it was passing, but the `attr(output, "headers")` dataframe is empty for a classified output. It's not empty for an extracted output; my hunch is because it `bind_rows` is used in `monkeylearn_extract()`, though I haven't confirmed that. I'll open an issue for adding a test to check that `nrow(attr(output, "headers")) != 0`!

**Comment by aedobbyn** [comment]
and also probably explains the `Unknown or uninitialised column: 'headers'.` you get when running the tests! (Feel like there's such a high false positive rate for warnings not actually mattering that I barely pay attention to them and half the time end up regretting it 😆 )

**Comment by maelle** [comment]
oooh good find! Bien joué ! 👏

**Comment by aedobbyn** [comment]
Merci!

**Comment by aedobbyn** [comment]
Since we're depending on a few tidyverse packages at this point I think this issue can be closed for now, though happy to reopen later down the line if we want to un-dependify!

**Comment by maelle** [comment]
I agree!
