### ISSUE TITLE
change the default texts per request value to 200 for all functions

### ISSUE THREAD

**Issue by aedobbyn** [ropensci/monkeylearn#34]

**Comment by maelle** [comment]
+ could you add a link to Monkeylearn docs in our docs to explain why we put it to 200?

**Comment by aedobbyn** [comment]
Oh yes, great point! Will do.

**Comment by aedobbyn** [comment]
I'm thinking we should only give the user a warning if they send >200 requests rather than error out because monkeylearn may update this value or change their pricing scheme such that some users would be able to go over the 200 limit. Another option would be to add a boolean argument like `ignore_max` that the user could set to true if they willfully wanted to send more than 200 -- this way they wouldn't need to suppress warnings.

**Comment by maelle** [comment]
Ah good point, dodocumented warning sounds good!

**Comment by aedobbyn** [comment]
Cool cool. I ended up setting `texts_per_req` to null by default. If it's not supplied and the length of the texts is > 200, then it's set to 200 and if less than 200 it's set to the length of the text:

```
  if (is.null(texts_per_req)) {
    if (length1 < 200) {
      texts_per_req <- length1
    } else {
      texts_per_req <- 200
    }
  } else if (!is.numeric(texts_per_req) || texts_per_req <= 0 || texts_per_req > length1) {
    stop("Error: texts_per_req must be a whole positive number less than or equal to the number of texts.")
  } else if (texts_per_req > 200) {
    warning("Maximum 200 texts recommended per rquests.")
  }
```
