### ISSUE TITLE
Add a test to check that the headers dataframe isn't empty

### ISSUE THREAD

**Issue by aedobbyn** [ropensci/monkeylearn#36]

**Comment by maelle** [comment]
related to a bug you observed?

**Comment by aedobbyn** [comment]
Yes! I should have mentioned in the description. In #33 I say that `dplyr::bind_rows` is currently used in lines 107 and 108 of `extractor.R` on master. This should explain why headers from `monkeylearn_classify()` were an empty tibble those from `monkeylearn_extract()` were not 🎉
