### ISSUE TITLE
Error with extractor id ex_dqRio5sG

### ISSUE THREAD

**Issue by aedobbyn** [ropensci/monkeylearn#39]
Trouble creating `output_nested`  from `output$result` in `monkey_extract()` with this particular extractor. 

```
res <- output$result
output_nested <- tibble::as_tibble(list(resp = res))
```
`Error: Column `resp` must be a 1d atomic vector or a list`

`res` is a 2x11 dataframe of columns `dates`, `links`, `phones`, `ipv6s`, etc.

**Comment by maelle** [comment]
https://app.monkeylearn.com/main/extractors/ex_dqRio5sG/

(link for my own use)

**Comment by aedobbyn** [comment]
```
      dates       links     phones ipv6s hex_colors  ips        credit_cards prices   times           emails bitcoin_addresses
1 April 16, example.com 15555 9876  NULL       NULL NULL 4242-4242-4242-4242    $10 10:00am john@example.com              NULL
2 April 16, example.com 16655 9876  NULL       NULL NULL 4242-4232-4242-4242        10:00am mary@example.com              NULL
#> Error: <text>:1:19: unexpected symbol
#> 1:       dates       links
#>                       ^
```

Bit more context on what this dataframe looks like in the debugger. It's of class `data.frame` but for whatever reason can't be turned into a tibble.

**Comment by maelle** [comment]
when this is solved update vignette and website

**Comment by aedobbyn** [comment]
Ok -- I can take another pass at it but I don't remember being confident I could solve this 😔

**Comment by maelle** [comment]
Ok, please add what you tried here and I can have a look next week. I hope we can solve it but otherwise it's not too bad, IIRC the same extractor works with the old functions 💅

**Comment by aedobbyn** [comment]
I think the issue is that the entire result is NULL.  We'll need to map `purrr::map_df(replace_x)` (or some equivalent) over it to replace the NULLs with NAs.

**Comment by aedobbyn** [comment]
Closed in https://github.com/ropensci/monkeylearn/pull/95

**Comment by maelle** [comment]
Well done! 👏

**Comment by aedobbyn** [comment]
Thanks! 😊
