### ISSUE TITLE
Investigate empty headers dataframes

### ISSUE THREAD

**Issue by aedobbyn** [ropensci/monkeylearn#40]

**Comment by maelle** [comment]
more details? 😸

**Comment by aedobbyn** [comment]
Yes, sorry! The `expect_gte(nrow(attr(output, "headers")), 1)` tests are failing in `test_monkey_output.R` (commented out for now). They're passing in `test_output.R`, though, not sure why. Maybe something to do with a difference between `monkeylearn_parse()` and `monkeylearn_parse_each()`
