### ISSUE TITLE
Pare down the README to just installation and minimal examples and link to pkgdown articles

### ISSUE THREAD

**Issue by aedobbyn** [ropensci/monkeylearn#53]

**Comment by maelle** [comment]
Or if we make a pkgdown website, make the README minimal and link there to vignettes (= pkgdown articles) 🤔

**Comment by aedobbyn** [comment]
Oh yes! Love it. I'll change the title of this to pare down the README to just installation and minimal examples and link to pkgdown articles if that sounds good to you?

**Comment by maelle** [comment]
Yes, perfect! 

You can even create the pkgdown website if you want. 😉 But otherwise I can do that next week, it's just a few lines of code and a setting of the repo here.

**Comment by aedobbyn** [comment]
Ooh awesome, I've never done it before but I can give it a shot!

**Comment by maelle** [comment]
I did it but you can update the website later :wink:
