### ISSUE TITLE
use ratelimitr?

### ISSUE THREAD

**Issue by maelle** [ropensci/monkeylearn#57]
See https://github.com/ropensci/monkeylearn/issues/1

I also need to check whether the throttle limit depends on the plan.

What's been done in `opencage` https://github.com/dpprdan/opencage/commit/d44f6d190033b596c49c9f786d819901b60e5916

https://github.com/ropensci/opencage/issues/32

**Comment by maelle** [comment]
For that I will ask the user to add another environment variable MONKEYLEARN_PLAN that will be either "free", "team" or "business". 

If the variable doesn't exist there will be warning indicating the user should add it. By default it will be "free" (so it won't fail if there is no environment variable)

There will be two rates but `ratelimitr` handles that well. From the API docs "There is a maximum amount of requests per minute that you can make to the API depending on your plan: 20 for the Free plan, 60 for the Team plan and 120 for the Business plan. The API is limited to 5 concurrent requests per second."

**Comment by maelle** [comment]
Now that it works (push to come) I guess I could remove the code that handles the 429 codes, what do you think @aedobbyn ?

**Comment by maelle** [comment]
Another question for you @aedobbyn ... I see there can be special snowflakes https://monkeylearn.com/pricing/ whereas my current code doesn't have that. What would you recommend? Setting rate as an argument which will be confusing for most users? Or propose having an environment variable MONKEYLEARN_RATE when MONKEYLEARN_PLAN is "enterprise"?

**Comment by dpprdan** [comment]
Just saw the reference in opencage so chipping in here. ICYMI, regarding the two limits 

> 20 for the Free plan, 60 for the Team [...]. The API is limited to 5 concurrent requests per second."

ratelimitr supports multiple limits, see the [Readme](https://github.com/tarakc02/ratelimitr)/vignette.

**Comment by maelle** [comment]
I saw and use that, this is so cool, `ratelimitr` is great.

Our problem here is rather finding the user-friendliest way to deal with special ❄️ plans 😂

**Comment by aedobbyn** [comment]
Still waiting to hear back from MonkeyLearn re: a call to get either a) users' max per minute rates as well as their total number of monthly queries or b) a list of standard plans and their current rate limits and query limits.

Re: removing `monkeylearn_check()` which checks if `req$status_code == 429` I don't see any harm in keeping it in there just in case we erroneously infer that the user has a higher rate threshold than they actually do and the service throttles them (i.e. set `monkeylearn_rate` incorrectly).
