### ISSUE TITLE
updates NEWS for 0.2.0

### ISSUE THREAD

**Issue by maelle** [ropensci/monkeylearn#78]
Let's keep track of things here first maybe?

* ratelimitr

* your new functions (should come first actually)

* your bug fixes

* pkgdown website

* verbose

**Comment by maelle** [comment]
Next time we should do this in each pull request I guess 🤔

**Comment by aedobbyn** [comment]
Haha yeah, I guess like tests it's better to do as you go? 

I think this list looks good. If I think of anything else I'll add here!

**Comment by maelle** [comment]
Feel free to make "

your new functions (should come first actually)

your bug fixes" more explicit 🙏 😉 

I agree, this is *exactly* like tests!

**Comment by aedobbyn** [comment]
👌 👌 👌

**Comment by aedobbyn** [comment]
Should mention `.keep_all` as well here, now

**Comment by maelle** [comment]
It's gonna be such an impressive NEWS.md

**Comment by aedobbyn** [comment]
Added a few bullets to [NEWS](https://github.com/ropensci/monkeylearn/blob/dev/NEWS.md); looped `verbose` bullets into discussions of the new functions but can pull them out if it's worth a separate bullet.

**Comment by maelle** [comment]
Looks good, thanks!

**Comment by aedobbyn** [comment]
@maelle seems like maybe an answer to our quandry? Would mean I'd need to make more informative commit messages though 😆 
https://twitter.com/krlmlr/status/980722338172932096

**Comment by maelle** [comment]
I know right :joy:
