### ISSUE TITLE
Stop having default IDs? Or have a warning?

### ISSUE THREAD

**Issue by maelle** [ropensci/monkeylearn#79]
This way we'd still have a default ID for tests but the user would need to think about the classifier or extractor, which I think makes more sense?

**Comment by aedobbyn** [comment]
I like this, because it will make people think critically about which ID they're using. At the same time, I think we want to reduce friction for people who just want to give the package a spin. So maybe a warning if `verbose` is TRUE, which it is by default?

**Comment by maelle** [comment]
Cool! Could you add it? Otherwise I will.

**Comment by aedobbyn** [comment]
Yep, I can do it!

**Comment by aedobbyn** [comment]
Originally messaged no matter the classifier used in https://github.com/ropensci/monkeylearn/commit/64a7b26f3848070dc5bf1d50e9d4047108eee7de but then changed to only message when the default was used in https://github.com/ropensci/monkeylearn/commit/6dd3aa8beed0da0c2b72889f2641ac1e83caaef8. Happy to go back to the first option, though

**Comment by maelle** [comment]
I think the second one is better, so let it as is. Thanks a lot!

**Comment by aedobbyn** [comment]
Great! 👌
