### ISSUE TITLE
How to help users migrate towards the new functions

### ISSUE THREAD

**Issue by maelle** [ropensci/monkeylearn#81]
* Add sthg to the old functions docs

* Add a message?

**Comment by aedobbyn** [comment]
I like both of these! Think we should only add a message if `verbose` is true?

**Comment by maelle** [comment]
Good idea! Do you want to add it?

**Comment by aedobbyn** [comment]
Sure! I'll open an issue

**Comment by aedobbyn** [comment]
Closing this now that #94 is open
