### ISSUE TITLE
make unnest = TRUE the default?

### ISSUE THREAD

**Issue by maelle** [ropensci/monkeylearn#82]

**Comment by aedobbyn** [comment]
I'm good with this!

**Comment by maelle** [comment]
Cool, could you also remove all the "unnest=TRUE" from the vignette? Otherwise I will. :-)

**Comment by aedobbyn** [comment]
I removed them from the vignette back in https://github.com/ropensci/monkeylearn/commit/2f839d5b340b71255dae7b90b8657b65196b82b1 but left one of them in there for illustrative purposes (though now that I look at it again we may want to do the same thing for the example right above it as well)

**Comment by maelle** [comment]
Thank you!
