### ISSUE TITLE
Debug the "The following indices were empty strings" output

### ISSUE THREAD

**Issue by aedobbyn** [ropensci/monkeylearn#85]
We want to paste together a list of all the indices that will be thrown out; wrong variable being used currently.
Also thinking we won't want to show too big of a message; maybe limit to 20 indices and truncate the rest?

**Comment by aedobbyn** [comment]
Went with limiting to 20. It'll be clear to the user in their output which of the strings were empty because they'll be returned in the output, so they can just `filter` to the empties themselves. Otherwise I'd say we should save the whole list of empties as an attribute or something that they can access if they want to see the full list.

**Comment by maelle** [comment]
I think it's great as is, because yep the user can filter that themselves.

Maybe you could open an issue about adding a example in the docs for v0.3.0 if you think that's useful.

**Comment by aedobbyn** [comment]
Nice idea, will do
