### ISSUE TITLE
When trying to unnest an output whose `resp` is entirely NAs, we get an error

### ISSUE THREAD

**Issue by aedobbyn** [ropensci/monkeylearn#90]
`Error: All nested columns must have the same number of elements.`

Need to put a check in before

```
if (unnest == TRUE) {
    results <- tidyr::unnest(results)
}
```

to make sure that `results$resp` isn't just NAs.

**Comment by aedobbyn** [comment]
Closed with https://github.com/ropensci/monkeylearn/commit/da00681960dcb27d8466e4593c35efdccf7b7efa

**Comment by maelle** [comment]
Good catch! 🎣
