### ISSUE TITLE
Add a message into older monkeylearn_ functions when verbose is true encouraging users to uses new functions

### ISSUE THREAD

**Issue by aedobbyn** [ropensci/monkeylearn#93]

**Comment by aedobbyn** [comment]
I made the default value of `verbose` TRUE -- not sure if we want to undo that change or not.

**Comment by maelle** [comment]
I think it's a good move here, since we want to be sure the message is seen.

**Comment by aedobbyn** [comment]
Ok!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
