### ISSUE TITLE
Reformat code (especially monkey_extract)

### ISSUE THREAD

**Issue by aedobbyn** [ropensci/monkeylearn#99]
Maybe use `lintr` or `formatR`

**Comment by maelle** [comment]
I'd recommend `styler` actually!

**Comment by maelle** [comment]
And then maybe we could add a `lintr` unit test to be really strict with ourselves hehe. Note that lintr-bot would then comment on each PR so it might become tedious? There's a lintr unit test in `opencage`.

**Comment by aedobbyn** [comment]
Cool, reformatted with `styler`! There was a bug I'm going to repro and submit an issue for which I think was related to the accent on "Hauràs"; that's why the first build failed.

Re: `lintr` I'm fine with either way. We do have a lot of lines > 80 characters so we'd want to specify a non-default config, I think.

**Comment by maelle** [comment]
Oh interesting about the accent, good catch!

Do these long lines have a good reason to be long? We could escape them with # nolint

**Comment by aedobbyn** [comment]
Yeah, it's a weird bug. Even shortening the long string by one line fixes it (see https://github.com/r-lib/styler/issues/383). So we could just shorten the long string and `styler::style_pkg()` should work just fine
